# Implement Task Workflow Configuration
name: implement-task
description: "Implementation-only workflow with 4 strategy options: full-auto-with-pr (fastest), full-auto-without-pr (auto with PR control), semi-auto-with-commit (review between phases), manual (full control)"
author: "SDD Module"

# Paths
installed_path: "{project-root}/bmad/sdd/workflows/implement-task"
template: false # Action workflow - no template
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Critical variables from config
config_source: "{project-root}/bmad/sdd/config.yaml"
output_folder: "{config_source}:output_document_path"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# SDD-specific configuration
commit_msg_template_path: "{config_source}:commit_msg_template_path"
pr_template_path: "{config_source}:pr_template_path"
write_unit_test_along_with_task: "{config_source}:write_unit_test_along_with_task"

# Required input documents
required_inputs:
  - tech_spec_path: "Path to tech spec document (from create-tech-spec or dev-flow workflow)"

# Optional parameters (can be passed from dev-flow)
optional_inputs:
  - workflow_strategy: "Implementation strategy: 'full-auto-with-pr', 'full-auto-without-pr', 'semi-auto-with-commit', or 'manual' (default: ask user)"
  - jira_task_number: "Jira task number (extracted from tech spec if not provided)"

# Invocation control
standalone: true
can_be_invoked: true # Can be invoked by other workflows (e.g., dev-flow)
