# Analyze Architecture Workflow Configuration
name: analyze-architecture
description: "Progressive architecture documentation workflow - analyze what you need, when you need it. Generates concise, AI-focused documentation organized in fe/, be/, db/, and other layers."
author: "SDD Module"

# Paths
installed_path: "{project-root}/bmad/sdd/workflows/analyze-architecture"
template: false # Action workflow - generates multiple documents dynamically
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Critical variables from config
config_source: "{project-root}/bmad/sdd/config.yaml"
output_folder: "{config_source}:output_document_path"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# SDD-specific configuration
tech_architecture_doc_path: "{config_source}:tech_architecture_doc_path"

# Analysis scope options
analysis_scope_types:
  - full_project: "Generate high-level overview of entire codebase"
  - specific_layer: "Focus on frontend, backend, database, or infrastructure layer"
  - specific_implementation: "Analyze particular component, API, service, or feature"

# Layer structure (flat by default, user can create subfolders)
default_layers:
  - fe: "Frontend"
  - be: "Backend"
  - db: "Database"
  - infra: "Infrastructure"
  - shared: "Shared utilities and cross-cutting concerns"

# Documentation principles
documentation_principles:
  - Progressive: "Document incrementally as needed, not all at once"
  - Concise: "50-300 lines per file, focus on AI-useful patterns"
  - Structured: "Organized by layer (fe/, be/, db/), flat by default"
  - Flexible: "User can modify filenames, structure, merge/split decisions"
  - Actionable: "Include patterns, conventions, gotchas, dependencies, examples"

# Content guidelines
content_focus:
  include:
    - "Coding patterns and conventions"
    - "Common utilities and hooks usage"
    - "API conventions (props, signatures)"
    - "Gotchas and pitfalls"
    - "Dependencies and libraries"
    - "One concise code example per concept"
  exclude:
    - "Full source code"
    - "Historical evolution"
    - "Verbose explanations"
    - "Multiple redundant examples"
    - "Design discussions and debates"

# File length targets
length_targets:
  simple: "50-100 lines"
  medium: "100-200 lines"
  complex: "200-300 lines (consider splitting if larger)"

# Relatedness thresholds for grouping
relatedness_thresholds:
  high: ">70% shared logic → MERGE"
  medium: "50-70% shared logic → ASK USER"
  low: "<50% shared logic → SEPARATE"

# Invocation control
standalone: true
