# Analyze Architecture Workflow Configuration
name: analyze-architecture
description: "Deep analysis of brownfield project architecture, generating structured technical documentation across multiple topic-specific files for AI reference during implementation"
author: "SDD Module"

# Paths
installed_path: "{project-root}/bmad/sdd/workflows/analyze-architecture"
template: false # Action workflow - generates multiple documents dynamically
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Critical variables from config
config_source: "{project-root}/bmad/sdd/config.yaml"
output_folder: "{config_source}:output_document_path"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# SDD-specific configuration
tech_architecture_doc_path: "{config_source}:tech_architecture_doc_path"

# Architecture analysis configuration
analysis_scope:
  - full_project: "Analyze entire project"
  - specific_directory: "Analyze specific directory or module"
  - frontend_only: "Analyze frontend layer only"
  - backend_only: "Analyze backend layer only"

# Document categories that may be generated
document_types:
  core:
    - overview: "Project overview, tech stack, high-level architecture"
    - structure: "Directory structure, module organization, naming conventions"
  backend:
    - backend-overview: "Backend architecture overview"
    - backend-api: "API design, routing patterns, middleware"
    - backend-services: "Service layer, business logic organization"
    - backend-data-access: "Repository/DAO patterns, ORM usage"
    - backend-auth: "Authentication and authorization mechanisms"
    - backend-error-handling: "Error handling patterns and strategies"
  frontend:
    - frontend-overview: "Frontend architecture overview"
    - frontend-components: "Component design patterns, component library"
    - frontend-state: "State management patterns (Redux/Zustand/Context)"
    - frontend-routing: "Routing architecture, navigation patterns"
    - frontend-api-integration: "API calling patterns, data fetching"
    - frontend-styling: "Styling architecture, theme systems"
  supporting:
    - database: "Database schema, relationships, migration strategy"
    - testing: "Testing strategy, test architecture, coverage conventions"
    - deployment: "Deployment process, environment config, CI/CD"
    - conventions: "Code style, naming conventions, best practices"

# Invocation control
standalone: true
