# Product Flow Workflow Configuration
name: product-flow
description: "Transform product requirements into structured PRD with Epic/Story/Task breakdown"
author: "SDD Module"

# Paths
installed_path: "{project-root}/bmad/sdd/workflows/product-flow"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Critical variables from config
config_source: "{project-root}/bmad/sdd/config.yaml"
output_folder: "{config_source}:output_document_path"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# SDD-specific configuration
jira_info_path: "{config_source}:jira_info_path"
prd_template_path: "{config_source}:prd_template_path"

# Output configuration
default_output_file: "{output_folder}/prd/prd-{jira_proj}-{jira_number}-{scope_name}-{{date}}.md"

# Optional input documents
recommended_inputs:
  - jira_ticket: "Jira ticket number or manual requirement input"
  - architecture_docs: "{config_source}:tech_architecture_doc_path"

# Invocation control
standalone: true
